### ISSUE TITLE
[BUG] RuntimeError: protection exception (16782388)

### ISSUE THREAD

**Issue by xiene** [dashingsoft/pyarmor#1007] opened 2023-03-25 02:59 UTC
under pyarmor 8.0.10 and python 3.11.2
I got the following error when running some obfuscated codes.

---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: protection exception (16782388)

Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK  
---------------------------

How can I resolve this error?

**Comment by jondy** [comment] 2023-03-25 03:23
What options used to obfuscate the scripts?

**Comment by xiene** [comment] 2023-03-25 03:31
I used the "pyarmor gen" command.

**Comment by jondy** [comment] 2023-03-25 05:12
A quick workaround is disable this restrict by this command
```
pyarmor cfg restrict_module=0
```

Then obfuscate the scripts again.

This bug will be fixed in next release. After new version is released, reset the default value
```
pyarmor cfg --reset restrict_module
```

If you could provide a simple script to reproduce this issue, that would be very helpful. I guess it's caused by importing a module in a function, not the module level.

**Comment by xiene** [comment] 2023-03-25 07:12
I ran "pyarmor cfg restrict_module=0" then I obfuscated the scripts again.
But I got the same error.
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: protection exception (16782388)

I don't want to expose the script as there is no point in obfuscating it. e-mail it to you.

**Comment by jondy** [comment] 2023-03-25 08:54
Could you show the full command to obfuscate the scripts?

I have checked the source, if `pyarmor cfg restrict_module=0` works, this error should not be raised.

**Comment by xiene** [comment] 2023-03-25 11:29
I ran the following command to obfuscate the scripts.
pyarmor cfg restrict_module=0
pyarmor gen common.py
pyarmor gen post_adjust_rate.py

**Comment by jondy** [comment] 2023-03-25 13:26
Anyway, please Upgrade Pyarmor to 8.0.15 with pyarmor.cli.core==1.0.6

Now it's urgent release for Pyarmor 8.0. For next minor version 8.1, it will be full tested before release.

Then run this command once
```
pyarmor cfg --reset restrict_module
```

And obfuscate the scripts
```
pyarmor gen common.py post_adjust_rate.py
```

**Comment by xiene** [comment] 2023-03-26 02:05
Thank you. I can now run obfuscated scripts.

**Closed** 2023-03-26 02:06 UTC
Labels: bug
