### ISSUE TITLE
ERROR    unknown token error 3

### ISSUE THREAD

**Issue by hansroh** [dashingsoft/pyarmor#1977] opened 2024-11-05 02:03 UTC
Suddenly, raised error today.

```python
# foo.py
print ('IT WORKS')
```

```shell
pyarmor gen foo.py
INFO     Python 3.8.10
INFO     Pyarmor 9.0.3 (basic), 004815, KrackNet
INFO     Platform linux.x86_64
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
ERROR    unknown token error 3

cat pyarmor.error.log 
559675 MainProcess 2024-11-05 10:59:10,907
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 767, in main
    main_entry(sys.argv[1:])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 755, in main_entry
    return args.func(ctx, args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyarmor/cli/__main__.py", line 246, in cmd_gen
    builder.process(options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyarmor/cli/generate.py", line 181, in process
    self.ctx.runtime_key = self.generate_runtime_key()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyarmor/cli/generate.py", line 95, in generate_runtime_key
    return Pytransform3.generate_runtime_key(self.ctx, outer)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pyarmor/cli/core/__init__.py", line 105, in generate_runtime_key
    return m.generate_runtime_key(ctx, outer)
  File "<maker>", line 726, in generate_runtime_key
  File "<maker>", line 266, in build
RuntimeError: unknown token error 3
```

On Python 3.11, it is same.
```shell
pyarmor gen  foo.py
INFO     Python 3.11.0
INFO     Pyarmor 9.0.3 (basic), 004815, KrackNet
INFO     Platform linux.x86_64
INFO     search inputs ...
INFO     find script foo.py
INFO     find 1 top resources
ERROR    unknown token error 3
```

BUT my CI license is works fine.

I reregistered pyarmor, it dosen't work at all.
```shell
rm -rf ~/.pyarmor
pyarmor reg pyarmor-regfile-4815.zip
```

**Comment by CharlieGuo** [comment] 2024-11-05 03:01
Me too. Same issue.

**Comment by jakjarvis** [comment] 2024-11-05 03:39
Same here - same trace and error log. Also using a basic license.

**Comment by jondy** [comment] 2024-11-05 03:57
Hi all, do you check Pyarmor 9 upgrade notes #1958, and upgrade the regfile?

**Comment by jondy** [comment] 2024-11-05 05:00
Reproduced, it's fixing...

**Comment by hansroh** [comment] 2024-11-05 05:01
> Hi all, do you check Pyarmor 9 upgrade notes #1958, and upgrade the regfile?

Yes.

**Comment by jakjarvis** [comment] 2024-11-05 05:02
Hi Jondy,

My license was only activated last week, originally and currently on v9, and is not currently used in a CI/CD pipeline. On the day I activated it, I was able to use it on multiple machines (my local windows PC and our linux server). However today it returns the above error on my local PC, running exactly the same build commands as were used last week. From my understanding of the upgrade notes.

I don't believe any of the notes in #1958 are applicable here.

**Comment by 2107708125** [comment] 2024-11-05 05:31
I also have the same problem
INFO     Python 3.11.9
INFO     Pyarmor 9.0.3 (basic), 004842, mmc
INFO     Platform windows.x86_64
INFO     search inputs ...
INFO     find script mmc.pyw
INFO     find 1 top resources
ERROR    unknown token error 3

7864 MainProcess 2024-11-05 13:22:35,772
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 767, in main
    main_entry(sys.argv[1:])
  File "C:\Program Files\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 755, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 246, in cmd_gen
    builder.process(options)
  File "C:\Program Files\Python311\Lib\site-packages\pyarmor\cli\generate.py", line 181, in process
    self.ctx.runtime_key = self.generate_runtime_key()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyarmor\cli\generate.py", line 95, in generate_runtime_key
    return Pytransform3.generate_runtime_key(self.ctx, outer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 105, in generate_runtime_key
    return m.generate_runtime_key(ctx, outer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<maker>", line 726, in generate_runtime_key
  File "<maker>", line 266, in build
RuntimeError: unknown token error 3

**Comment by jondy** [comment] 2024-11-05 06:05
I have found the problem, it need update pyarmor.cli.core.

I'm building a quick fix version, it will be released in several hours.

Sorry for this issue.

**Comment by jondy** [comment] 2024-11-05 07:30
Please upgrade `pyarmor.cli.core` to 7.6.1 to fix this issue. For example,
```
pip install pyarmor.cli.core~=7.6.1
```

**Comment by hansroh** [comment] 2024-11-05 10:47
It works!

**Comment by jakjarvis** [comment] 2024-11-05 21:00
Works for me too - thanks for the quick fix Jondy!

**Closed** 2024-11-07 00:53 UTC
Labels: bug
