### ISSUE TITLE
__del__ method of a class fails when obfuscated

### ISSUE THREAD

**Issue by mauvilsa** [dashingsoft/pyarmor#530] opened 2021-06-24 15:32 UTC
**Describe the bug**
When I create a class that implements a `__del__` method, when instantiating this class at the end of the script when the object is supposed to be deleted that method fails and its code is not run.

**To Reproduce**
pyarmor version: 6.3.6 (purchased) and also in 6.7.2 (trial)
python version: 3.6

For example with a script:

```python
import shutil
import tempfile
from dataclasses import dataclass

@dataclass
class MyData:
    tmpdir: str = None

    def __post_init__(self):
        self.del_tmpdir = False
        if self.tmpdir is None:
            self.tmpdir = tempfile.mkdtemp()
            self.del_tmpdir = True
            print(f'Created temp dir {self.tmpdir}')

    def __del__(self):
        if self.del_tmpdir:
            print(f'Removing temp dir {self.tmpdir}')
            shutil.rmtree(self.tmpdir)

data = MyData()
```

When I run it without obfuscation I get the following expected result:

```bash
$ python3 run.py 
Created temp dir /tmp/tmpyxbw8x05
Removing temp dir /tmp/tmpyxbw8x05
```

But if I obfuscate and then run it it fails:

```bash
$ pyarmor obfuscate run.py
INFO     PyArmor Version 6.7.2
INFO     Python 3.6.9
INFO     Target platforms: Native
INFO     Source path is "..."
INFO     Entry scripts are ['run.py']
INFO     Use cached capsule /home/.../.pyarmor/.pyarmor_capsule.zip
INFO     Search scripts mode: Normal
INFO     Save obfuscated scripts to "dist"
INFO     Read product key from capsule
INFO     Obfuscate module mode is 2
INFO     Obfuscate code mode is 1
INFO     Wrap mode is 1
INFO     Restrict mode is 1
INFO     Advanced value is 0
INFO     Super mode is False
INFO     Generating runtime files to dist/pytransform
INFO     Extract pytransform.key
INFO     Generate default license file
INFO     Copying /home/.../.local/lib/python3.6/site-packages/pyarmor/platforms/linux/x86_64/_pytransform.so
INFO     Patch library dist/pytransform/_pytransform.so
INFO     Patch library file OK
INFO     Copying /home/.../.local/lib/python3.6/site-packages/pyarmor/pytransform.py
INFO     Rename it to pytransform/__init__.py
INFO     Generate runtime files OK
INFO     Start obfuscating the scripts...
INFO            run.py -> dist/run.py
INFO     Insert shell line: #!/usr/bin/env python3
INFO     Insert bootstrap code to entry script dist/run.py
INFO     Obfuscate 1 scripts OK.

$ python3 dist/run.py 
Created temp dir /tmp/tmp0737exy0
Exception ignored in: <bound method MyData.__del__ of MyData(tmpdir='/tmp/tmp0737exy0')>
Traceback (most recent call last):
  File "<frozen run>", line 19, in __del__
NameError: name '__armor_enter__' is not defined
```

Note that the print inside `__del__` is not run and the directory is not removed. This is a problem since I exect code there to be executed.

**Comment by jondy** [comment] 2021-06-25 14:07
A quick workaround is not obfuscate `__del__`, just rename `__del__` to `lambda_del`, then assign it to `__del__`. For example
```python
    ...
    def lambda_del(self):
        if self.del_tmpdir:
            print(f'Removing temp dir {self.tmpdir}')
            shutil.rmtree(self.tmpdir)
      __del__ = lambda_del
```
All the function name starts with `lambda_` will not be obfuscated by Pyarmor

**Comment by mauvilsa** [comment] 2021-06-25 19:53
Thank you for the workaround. Though I am not really interested in changing my code just so that it works when obfuscated. I am more interested if this can be fixed in pyarmor and if so more or less when it would be available.

**Comment by jondy** [comment] 2021-06-25 22:08
I have not found the root cause, but if `dataclasses` uses some features changed by pyarmor, it's impossible to be fixed.

**Comment by jondy** [comment] 2021-06-25 22:19
I have not found the root cause, one possible reason is that the builtin function `__wrap_enter__` has been deleted during interpreter shutdown, refer to CPython decumentation
>`__del__()` can be executed during interpreter shutdown. As a consequence, the global variables it needs to access (including other modules) may already have been deleted or set to None. Python guarantees that globals whose name begins with a single underscore are deleted from their module before other globals are deleted; if no other references to such globals exist, this may help in assuring that imported modules are still available at the time when the __del__() method is called.

And if `dataclasses` uses some features changed by pyarmor, it's impossible to be fixed.

**Comment by mauvilsa** [comment] 2021-06-26 04:11
I tried changing the data class to a normal class and the problem persists. So the issue is not related to dataclasses.

**Comment by jondy** [comment] 2021-06-26 04:25
I have found the problem, this issue will be fixed in next version (v6.7.3)

**Comment by jondy** [comment] 2021-06-27 03:40
A pre-release version v6.7.3 has been released
https://pyarmor.readthedocs.io/en/latest/change-logs.html#dev

Note that for Python 3.7 and later, this issue still exists in non-super mode. Use super mode for these Python versions to solve this issue.

**Closed** 2021-07-05 09:45 UTC
Labels: bug

**Comment by tkornuta-nvidia** [comment] 2021-10-30 02:23
Hi @jondy it seems that the problem with destructors still exists in 6.8.1.

Moreover, after tracking it down, it is not only "de-obfuscation" the destructor, but also all methods and properties that it calls!

Here's simple example:
```
    def lambda_del(self):
        self.clear()
    
    __del__ = lambda_del
``
required to also `lambda_clear` and as it was calling other methods I had to change them too...
