### ISSUE TITLE
[BUG] Bitwise &,  >>, << Operators Dont Work On Compiled Exe

### ISSUE THREAD

**Issue by grinchify** [dashingsoft/pyarmor#1499] opened 2023-09-25 20:23 UTC
Using the following build command 

`pyarmor gen -e .30 --enable-bcc --enable-jit --private --recursive --period 1h --obf-code 2 a.py`

on the following code 

```
import random

def foo():
    ae = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    
    for t in range(16):
        if (3 & t) == 0:
            e = int(4294967296 * random.random())
        ae[t] = (e >> ((3 & t) << 3)) & 255

    r = 0

    n = [
        "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "0a", "0b", "0c", "0d", "0e", "0f",
        "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "1a", "1b", "1c", "1d", "1e", "1f",
        "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "2a", "2b", "2c", "2d", "2e", "2f",
        "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "3a", "3b", "3c", "3d", "3e", "3f",
        "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "4a", "4b", "4c", "4d", "4e", "4f",
        "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "5a", "5b", "5c", "5d", "5e", "5f",
        "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "6a", "6b", "6c", "6d", "6e", "6f",
        "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "7a", "7b", "7c", "7d", "7e", "7f",
        "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "8a", "8b", "8c", "8d", "8e", "8f",
        "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "9a", "9b", "9c", "9d", "9e", "9f",
        "a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "aa", "ab", "ac", "ad", "ae", "af",
        "b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "ba", "bb", "bc", "bd", "be", "bf",
        "c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "ca", "cb", "cc", "cd", "ce", "cf",
        "d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8", "d9", "da", "db", "dc", "dd", "de", "df",
        "e0", "e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9", "ea", "eb", "ec", "ed", "ee", "ef",
        "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "fa", "fb", "fc", "fd", "fe", "ff"
    ]

    d = [
        n[ae[r]], n[ae[r+1]], n[ae[r+2]], n[ae[r+3]], "-", n[ae[r+4]], n[ae[r+5]], "-", n[ae[r+6]], n[ae[r+7]], "-",
        n[ae[r+8]], n[ae[r+9]], "-", n[ae[r+10]], n[ae[r+11]], n[ae[r+12]], n[ae[r+13]], n[ae[r+14]], n[ae[r+15]]
    ]


    print("".join(d))

foo()
```

It compiles perfectly fine, however when running the obfuscated version, nothing gets printed out. After further investigation I think it is related to the bitwise operators.

**Comment by jondy** [comment] 2023-09-26 13:36
Got it, thanks. I'll check it.

**Comment by jondy** [comment] 2023-09-27 01:01
Please paste the first three logs about which includes Python version, Pyarmor version, and platform

I test it with Python 3.7/3.9 in darwin.x86_64, it works fine.

**Comment by grinchify** [comment] 2023-09-27 12:40
INFO     Python 3.10.11
INFO     Pyarmor 8.3.9 (pro), 
INFO     Platform windows.x86_64

**Comment by jondy** [comment] 2023-09-29 07:21
Could you provide the minimum options to reproduce this issue?

**Comment by grinchify** [comment] 2023-09-29 12:54
pyarmor gen --enable-bcc --obf-code 2 a.py   

Seems to be something with BCC

**Comment by jondy** [comment] 2023-09-29 13:26
Generally `--obf-code 2` is not required if `--enable-bcc`.

I'll check it to find the problem.

**Comment by VeNoMouS** [comment] 2023-10-11 23:19
@grinchify 
```python
    n = [
        "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "0a", "0b", "0c", "0d", "0e", "0f",
        "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "1a", "1b", "1c", "1d", "1e", "1f",
        "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "2a", "2b", "2c", "2d", "2e", "2f",
        "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "3a", "3b", "3c", "3d", "3e", "3f",
        "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "4a", "4b", "4c", "4d", "4e", "4f",
        "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "5a", "5b", "5c", "5d", "5e", "5f",
        "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "6a", "6b", "6c", "6d", "6e", "6f",
        "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "7a", "7b", "7c", "7d", "7e", "7f",
        "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "8a", "8b", "8c", "8d", "8e", "8f",
        "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "9a", "9b", "9c", "9d", "9e", "9f",
        "a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "aa", "ab", "ac", "ad", "ae", "af",
        "b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7", "b8", "b9", "ba", "bb", "bc", "bd", "be", "bf",
        "c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "ca", "cb", "cc", "cd", "ce", "cf",
        "d0", "d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8", "d9", "da", "db", "dc", "dd", "de", "df",
        "e0", "e1", "e2", "e3", "e4", "e5", "e6", "e7", "e8", "e9", "ea", "eb", "ec", "ed", "ee", "ef",
        "f0", "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "fa", "fb", "fc", "fd", "fe", "ff"
    ]
```
....

```python
n = [ f"{hex(i)[2:].zfill(2)}" for i in range(0, 256)]
```

**Comment by jondy** [comment] 2023-10-18 04:22
I tested it in MacOs and Linux with Python 3.10, it works fine.

I have no windows python 3.10 because it need Windows 10+.

And I check the source there is no special code for Windows for BCC mode.

So I close it until it could be reproduced.

**Closed by jondy** 2023-10-18 04:23 UTC
Labels: bug
