### ISSUE TITLE
Bugs while using --mix-str --enable-rft --assert-call

### ISSUE THREAD

**Issue by JiaPai12138** [dashingsoft/pyarmor#1090] opened 2023-04-05 04:03 UTC
Pyarmor 8.0.26 (pro)
Problem: **With either one of those additional options added, obfuscated scripts will get error**
```
--mix-str --enable-rft --assert-call
```

Command (with no errors):
```
pyarmor gen --enable-jit --enable-bcc --enable-themida test1.py
```

test1:
```
import os
from ctypes import (Structure, Union, byref, sizeof, windll, wintypes)
from sys import executable, exit
from time import sleep

from win32api import GetAsyncKeyState, GetSystemMetrics
from win32con import (  KEYEVENTF_KEYUP, KEYEVENTF_UNICODE, MOUSEEVENTF_ABSOLUTE,
                        MOUSEEVENTF_LEFTDOWN, MOUSEEVENTF_LEFTUP,
                        MOUSEEVENTF_MOVE, MOUSEEVENTF_RIGHTDOWN,
                        MOUSEEVENTF_RIGHTUP, MOUSEEVENTF_VIRTUALDESK,
                        MOUSEEVENTF_WHEEL, VK_END, VK_LEFT, VK_RIGHT)


class MOUSEINPUT(Structure):
    _fields_ = (('dx', wintypes.LONG),
                ('dy', wintypes.LONG),
                ('mouseData', wintypes.DWORD),
                ('dwFlags', wintypes.DWORD),
                ('time', wintypes.DWORD),
                ('dwExtraInfo', wintypes.WPARAM))


class KEYBDINPUT(Structure):
    _fields_ = (('wVk', wintypes.WORD),
                ('wScan', wintypes.WORD),
                ('dwFlags', wintypes.DWORD),
                ('time', wintypes.DWORD),
                ('dwExtraInfo', wintypes.WPARAM))

    def __init__(self, *args, **kwds):
        super(KEYBDINPUT, self).__init__(*args, **kwds)
        if not self.dwFlags & KEYEVENTF_UNICODE:
            self.wScan = windll.user32.MapVirtualKeyExW(self.wVk, 0, 0)


class HARDWAREINPUT(Structure):
    _fields_ = (('uMsg', wintypes.DWORD),
                ('wParamL', wintypes.WORD),
                ('wParamH', wintypes.WORD))


class INPUT(Structure):
    class _INPUT(Union):
        _fields_ = (('ki', KEYBDINPUT),
                    ('mi', MOUSEINPUT),
                    ('hi', HARDWAREINPUT))
    _anonymous_ = ('_input',)
    _fields_ = (('type', wintypes.DWORD),
                ('_input', _INPUT))


def Mouse(dwFlags=0x0001, dx=0, dy=0, mouseData=0x000):
    me = INPUT(type=0, mi=MOUSEINPUT(dx=dx, dy=dy, dwFlags=dwFlags, mouseData=mouseData))
    return windll.user32.SendInput(1, byref(me), sizeof(me))


def Keyboard(vk_code, flags=0):
    x = INPUT(type=1, ki=KEYBDINPUT(wVk=vk_code, dwFlags=flags))
    return windll.user32.SendInput(1, byref(x), sizeof(x))


class win_sdipmk:
    def __init__(self):
        self.width = GetSystemMetrics(0)
        self.height = GetSystemMetrics(1)

    def char2vk(self, c: str) -> int:
        try:
            return windll.user32.VkKeyScanW(ord(c[0])) & 0xFF
        except: return 0

    def open(self):
        return 1

    def close(self):
        pass

    def move(self, x, y, absolute=False):
        MS_MOVE = MOUSEEVENTF_ABSOLUTE | MOUSEEVENTF_MOVE | MOUSEEVENTF_VIRTUALDESK if absolute else MOUSEEVENTF_MOVE
        x = int(abs(x*65536/self.width)) if absolute else int(x)
        y = int(abs(y*65536/self.height)) if absolute else int(y)
        return Mouse(MS_MOVE, x, y)

    def press(self, key):
        MS_KEY = MOUSEEVENTF_LEFTDOWN if key == 1 else MOUSEEVENTF_RIGHTDOWN
        return Mouse(MS_KEY)

    def release(self, key):
        MS_KEY = MOUSEEVENTF_LEFTUP if key == 1 else MOUSEEVENTF_RIGHTUP
        return Mouse(MS_KEY)

    def scroll(self, num):
        return Mouse(MOUSEEVENTF_WHEEL, 0, 0, -num*120)

    def down(self, ch):
        return Keyboard(self.char2vk(ch))

    def up(self, ch):
        return Keyboard(self.char2vk(ch), KEYEVENTF_KEYUP)


if __name__ == '__main__':
    mouse_keybd = win_sdipmk()
    mouse_keybd.press(1)
    mouse_keybd.move(100, 100)
    sleep(1)
    mouse_keybd.release(1)
    sleep(1)
    mouse_keybd.press(1)
    mouse_keybd.release(1)

    mouse_keybd.scroll(-1)
    sleep(1)

    mouse_keybd.down('d')
    sleep(1)
    mouse_keybd.up('d')

    exit(0)
```

**Comment by jondy** [comment] 2023-04-05 12:16
The latest version is `8.1.dev4`, maybe they're be fixed.

And if report a bug, it's better to provide more information, please refer to some nice bug reports #1089 

In this report, I don't know what's error message.

And the test script is smaller, it's better.

**Comment by jondy** [comment] 2023-04-06 15:12
Fixed `--enable-rft` and `--assert-call` issues in `8.1.dev5`, `--mix-str` issue isn't reproduced.

**Comment by jondy** [comment] 2023-04-07 23:57
Closed it because the issues here are reported by others

**Closed by jondy** 2023-04-07 23:57 UTC
Labels: bug
