### ISSUE TITLE
[BUG] `OSError: exception: access violation reading 0xE4442603` in windows.x86

### ISSUE THREAD

**Issue by pauloswear** [dashingsoft/pyarmor#1128] opened 2023-04-11 18:21 UTC
How to reproduce:

Create simple main.py script  with any print.
After create run: pyarmor gen --enable-rft main.py

**Error:**

16076 MainProcess 2023-04-11 15:19:20,223
Traceback (most recent call last):
  File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
    main_entry(sys.argv[1:])
  File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
    args.func(ctx, args)
  File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
    builder.process(options, pack=args.pack)
  File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\generate.py", line 155, in process
    self._obfuscate_scripts()
  File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
    code = Pytransform3.generate_obfuscated_script(self.ctx, r)
  File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\core\__init__.py", line 48, in generate_obfuscated_script
    return m.generate_obfuscated_script(ctx, res)
  File "<maker>", line 761, in generate_obfuscated_script
  File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__init__.py", line 12, in process
    return meth(self, res, *args, **kwargs)
  File "<maker>", line 517, in process
  File "<maker>", line 517, in <listcomp>
  File "<rftmaker>", line 16, in process
  File "<rftmaker>", line 686, in process
  File "<rftmaker>", line 565, in _simple_refactor
  File "<rftmaker>", line 191, in visit_builtins
OSError: exception: access violation reading 0xE4442603

**Comment by jondy** [comment] 2023-04-11 23:02
Can't reproduce, please provide more information about platform, python version, pyarmor version. When run command `gen`, all of these print in the console. 

And please provide simple script with well format report if possible, refer to this nice bug report #1089

**Comment by pauloswear** [comment] 2023-04-12 14:49
**Versions**
> Python version: 3.7.9, x86
> Platform system: Windows 10 x64 build 18363.418


**License type**
> Pyarmor 8.1.1 (pro), ***, ***
> 
> License Type    : pyarmor-pro
> License No.     : pyarmor-vax-***
> License To      : ****
> 
> BCC Mode        : Yes
> RFT Mode        : Yes



**Executed command: pyarmor -d gen --enable-rft .\pyarmor_test\main.py**
> .
> └── pyarmor_test/
>     └── main.py


**Script main.py:**
> print("hello world")


**Runtime error:**
> INFO     Python 3.7.9
> INFO     Pyarmor 8.1.1 (pro), ****, *****
> DEBUG    Platform windows.x86
> DEBUG    native platform windows.amd64
> DEBUG    home path: C:\Users\Paulo\.pyarmor
> DEBUG    command options: {'no_runtime': False, 'enable_rft': True, 'inputs': ['main.py']}
> INFO     search inputs ...
> INFO     find script main.py
> INFO     find 1 top resources
> DEBUG    build package relations
> INFO     start to generate runtime files
> INFO     target platforms {'windows.amd64'}
> INFO     write dist\pyarmor_runtime_******\pyarmor_runtime.pyd
> INFO     patch runtime file
> DEBUG    patching runtime data at 648160
> DEBUG    patch runtime file OK
> INFO     generate runtime files OK
> INFO     start to obfuscate scripts
> INFO     process resource "main"
> INFO     obfuscating file main.py
> DEBUG    process inline marker
> CRITICAL unknown error, please check pyarmor.error.log
> ERROR    exception: access violation reading 0xE4442603
> 


**pyarmor.log.error:**
> 14108 MainProcess 2023-04-12 11:47:51,557
> Traceback (most recent call last):
>   File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 627, in main
>     main_entry(sys.argv[1:])
>   File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 615, in main_entry
>     args.func(ctx, args)
>   File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__main__.py", line 179, in cmd_gen
>     builder.process(options, pack=args.pack)
>   File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\generate.py", line 155, in process
>     self._obfuscate_scripts()
>   File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\generate.py", line 120, in _obfuscate_scripts
>     code = Pytransform3.generate_obfuscated_script(self.ctx, r)
>   File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\core\__init__.py", line 48, in generate_obfuscated_script
>     return m.generate_obfuscated_script(ctx, res)
>   File "<maker>", line 761, in generate_obfuscated_script
>   File "c:\users\paulo\appdata\local\programs\python\python37-32\lib\site-packages\pyarmor\cli\__init__.py", line 12, in process
>     return meth(self, res, *args, **kwargs)
>   File "<maker>", line 517, in process
>   File "<maker>", line 517, in <listcomp>
>   File "<rftmaker>", line 16, in process
>   File "<rftmaker>", line 686, in process
>   File "<rftmaker>", line 565, in _simple_refactor
>   File "<rftmaker>", line 191, in visit_builtins
> OSError: exception: access violation reading 0xE4442603
>

**Comment by jondy** [comment] 2023-04-12 14:57
Got it, thanks.

**Comment by jondy** [comment] 2023-04-13 04:15
Fixed in the next release `8.1.4`

**Comment by jondy** [comment] 2023-04-13 15:10
Fixed in `8.1.4`

**Closed** 2023-04-14 15:19 UTC
Labels: bug
