### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by NotTiie** [dashingsoft/pyarmor#642] opened 2021-12-10 15:21 UTC
I used "pyarmor obfuscate xspammer.py"

This is what happens when I run the script:

```
C:\Users\kaisi\Favorites\Συνδέσεις\Misc\Tools\XWARES\XSPAMMER\XSpammer++\free\dist>py xspammer.py
Traceback (most recent call last):
  File "<C:\Users\kaisi\Favorites\Συνδέσεις\Misc\Tools\XWARES\XSPAMMER\XSpammer++\free\dist\xspammer.py>", line 3, in <module>
  File "<frozen xspammer>", line 740, in <module>
  File "C:\Users\kaisi\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\kaisi\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\kaisi\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\kaisi\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by jondy** [comment] 2021-12-11 00:41
duplicate of #640

**Comment by jondy** [comment] 2021-12-11 00:44
Please refer to source encoding 
https://pyarmor.readthedocs.io/en/latest/questions.html#necessary-knowledges

**Closed by jondy** 2021-12-11 00:44 UTC
