### ISSUE TITLE
Can not import AES from Crypto.Cipher

### ISSUE THREAD

**Issue by usmanov-danil** [dashingsoft/pyarmor#772] opened 2022-06-21 14:35 UTC
On MacOS 12.3.1 run pyarmor to obfuscate the script inside the docker container, python 3.7, PyArmor 7.5.1

```
$ PYTHONOPTIMIZE=2 pyarmor obfuscate --advanced 5 --exclude core/internal/code/api/streamer.py --src="." -r --output=/new_app entry.py 
```
makes success obfuscation, but after running project I got such exception:
```
File "<frozen core.internal.code.services.encryption>", line 6, in spp_caller
AttributeError: module 'Crypto.Cipher' has no attribute 'AES'
```
Tried use pycrypto, pycryptodome and pycryptodomex. The same error.

**Comment by jondy** [comment] 2022-06-22 02:03
Fixed in pre-release v7.5.1, try to reinstall it
```
pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.5.1.zip
```

**Comment by usmanov-danil** [comment] 2022-06-22 08:03
The error still exists

**Comment by jondy** [comment] 2022-06-22 13:04
Try it again.

**Comment by jondy** [comment] 2022-06-23 00:55
I have uploaded new file, hope there is no any bug this time.

**Comment by usmanov-danil** [comment] 2022-06-23 08:07
Thank you for your work but now when I try to run my entry script I got Segmentation Fault

**Comment by jondy** [comment] 2022-06-23 09:11
Does it work with `--advanced 2`, not `--advanced 5`?

**Comment by usmanov-danil** [comment] 2022-06-23 10:56
Did not help, Segmentation Fault still exists

**Comment by jondy** [comment] 2022-06-23 12:32
Use online option `no-spp-mode` to ignore some modules.

**Comment by jondy** [comment] 2022-06-23 13:58
I think of one possible reason, refer to
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-jit

Because spp mode uses the feature like JIT-compile, and it may cause crash in Apple M1, signing the runtime library `pytransform.so` with the corresponding entitlement may fix this problem. 

I have no Apple M1 on hand, I can't verify this now.

**Comment by usmanov-danil** [comment] 2022-06-23 17:52
I use obfuscation in the ubuntu docker image on the MacBook with Intel i5 chip 2018

**Comment by jondy** [comment] 2022-06-24 00:27
Could you provide a simple test script to reproduce it?

**Comment by usmanov-danil** [comment] 2022-06-24 07:51
Sadly, I can not publish my code but I will try to create code sneapet. 

Also, today I got such error without changing my code:

```
#23 27.27 /tmp/pyarmor_frozen core.internal.code.filters.detection.detection_analyzer.c: In function ‘spp__filter_detections_32’:
#23 27.27 /tmp/pyarmor_frozen core.internal.code.filters.detection.detection_analyzer.c:342:191: error: ‘None’ undeclared (first use in this function)
#23 27.27          if (!(x = op_compare(f_vars, PyCmp_GT, op_floordiv(op_call(NULL, ld_attr(ld_global(f_vars, ld_value(m_consts[19])), ld_value(m_consts[20])), 1, 0, NULL, ld_item(ld_value(f_vars[5]), None), NULL), ld_value(m_consts[21])), op_mult(ld_value(f_vars[12]), ld_attr(ld_value(f_vars[3]), ld_value(m_consts[22])))))) break;
#23 27.27                                                                                                                                                                                                ^
#23 27.27 /tmp/pyarmor_frozen core.internal.code.filters.detection.detection_analyzer.c:160:40: note: in definition of macro ‘op_floordiv’
#23 27.27  #define op_floordiv(a, b)    op_binary(a, b, Py_nb_floor_divide)
#23 27.27                                         ^
#23 27.27 /tmp/pyarmor_frozen core.internal.code.filters.detection.detection_analyzer.c:342:191: note: each undeclared identifier is reported only once for each function it appears in
#23 27.27          if (!(x = op_compare(f_vars, PyCmp_GT, op_floordiv(op_call(NULL, ld_attr(ld_global(f_vars, ld_value(m_consts[19])), ld_value(m_consts[20])), 1, 0, NULL, ld_item(ld_value(f_vars[5]), None), NULL), ld_value(m_consts[21])), op_mult(ld_value(f_vars[12]), ld_attr(ld_value(f_vars[3]), ld_value(m_consts[22])))))) break;
#23 27.27                                                                                                                                                                                                ^
#23 27.27 /tmp/pyarmor_frozen core.internal.code.filters.detection.detection_analyzer.c:160:40: note: in definition of macro ‘op_floordiv’
#23 27.27  #define op_floordiv(a, b)    op_binary(a, b, Py_nb_floor_divide)
#23 27.27                                         ^
#23 27.28 ERROR    Command '['gcc', '-O3', '-c', '-fPIC', '-fno-asynchronous-unwind-tables', '-fno-unwind-tables', '-o', '/tmp/pyarmor_frozen core.internal.code.filters.detection.detection_analyzer.o', '/tmp/pyarmor_frozen core.internal.code.filters.detection.detection_analyzer.c']' returned non-zero exit status 1.

```

**Comment by jondy** [comment] 2022-06-24 11:07
Could you send the source of function `filter_dectection' in line 32 of file `core/internal.code/filters/detection/detection_analyzer.py` to pyarmor@163.com?

**Comment by jondy** [comment] 2022-06-25 16:02
Please try the latest pre-release version, I have fixed several bugs regarding to `with/lambda/nest function/comprehension`.

**Comment by usmanov-danil** [comment] 2022-06-27 07:47
```
#23 20.19 INFO     Generating spp code for <frozen core.internal.code.abstract> ...
#23 20.19 DEBUG    Traverse syntax tree
#23 20.19 DEBUG    Find 0 available functions
#23 20.19 INFO     No any function available for sppmode in this module
#23 20.20 Traceback (most recent call last):
#23 20.20   File "/usr/local/bin/pyarmor", line 8, in <module>
#23 20.20     sys.exit(main_entry())
#23 20.20   File "/usr/local/lib/python3.7/dist-packages/pyarmor/pyarmor.py", line 1595, in main_entry
#23 20.20     main(sys.argv[1:])
#23 20.20   File "/usr/local/lib/python3.7/dist-packages/pyarmor/pyarmor.py", line 1587, in main
#23 20.20     args.func(args)
#23 20.20   File "/usr/local/lib/python3.7/dist-packages/pyarmor/pyarmor.py", line 744, in _obfuscate
#23 20.20     plugins=plugins, suffix=suffix, sppmode=sppmode)
#23 20.20   File "/usr/local/lib/python3.7/dist-packages/pyarmor/utils.py", line 1068, in encrypt_script
#23 20.20     sppmode=sppmode, reforms=reforms)
#23 20.20   File "/usr/local/lib/python3.7/dist-packages/pyarmor/cobuilder.py", line 45, in build_co_module
#23 20.20     return build_co_module(lines, modname, kwargs)
#23 20.20 TypeError: build_co_module() takes 2 positional arguments but 3 were given
------
executor failed running [/bin/bash -c pyarmor -d obfuscate --advanced 5 --exclude core/assembly/compile.py,core/internal/code/dbutils,core/internal/__init__.py,core/internal/code/__init__.py,stl/__init__.py,core/internal/code/api/__init__.py,core/internal/code/api/streamer.py --src="." -r --output=/new_app entry.py]: exit code: 1

```

**Comment by jondy** [comment] 2022-06-27 11:06
Please replace  "/usr/local/lib/python3.7/dist-packages/pyarmor/cobuilder.py", line 45 with
```
            return build_co_module(lines, modname, **kwargs)
```

**Comment by usmanov-danil** [comment] 2022-06-27 11:37
Builded but, when I run app, I also got Segmentation fault.

**Comment by jondy** [comment] 2022-07-27 06:14
@usmanov-danil I have fixed some big issues about spp mode, here it's a pre-release v7.6.0, try it freely

pip install https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.6.0.zip

**Comment by lolhesap** [comment] 2022-07-27 18:44
> @usmanov-danilspp moduyla ilgili bazı büyük sorunları düzelttim, işte bu bir ön sürüm v7.6.0'dır, özgürce deneyin
> 
> pip kurulumu https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-7.6.0.zip

my app was not working in spp mode but now working update fixed my problem, i hope fixed for him gl

**Closed** 2022-07-28 10:07 UTC
Labels: bug
