### ISSUE TITLE
[BUG] inline class definition not working in linux.aarch64

### ISSUE THREAD

**Issue by hiddify1** [dashingsoft/pyarmor#1083] opened 2023-04-04 06:41 UTC
If we have the following in the code, it will show the following exception:

`class DynamicForm(FlaskForm):pass`

CRITICAL unknown error, please check pyarmor.error.log
ERROR    'NoneType' object has no attribute 'offset'

but if we convert it to 

```
class DynamicForm(FlaskForm):
    pass
```

it will work.

In addition would you please the line number which has a problem in the log?

**Comment by jondy** [comment] 2023-04-04 06:44
Which python version is used?

**Comment by jondy** [comment] 2023-04-04 08:27
I also can't reproduce this issue by Python 3.8, 3.10, 3.11

**Comment by hiddify1** [comment] 2023-04-07 07:08
i tested in ubuntu aarch64 python3.10

**Comment by jondy** [comment] 2023-04-07 08:35
Got it, I'll check and fix aarch64 platform bug later.

**Comment by jondy** [comment] 2023-04-11 02:49
Reproduced and will be fixed in next version.

**Comment by jondy** [comment] 2023-04-11 23:46
Fixed it in `8.1.2`

**Closed** 2023-04-17 06:23 UTC
Labels: bug
