### ISSUE TITLE
[BUG]  <built-in function get_hd_info> returned a result with an exception set

### ISSUE THREAD

**Issue by tagnelli** [dashingsoft/pyarmor#1476] opened 2023-09-15 08:43 UTC
Hello,

We are having trouble registering a group license on a Windows Virtual Machine.

- `pyarmor reg -p non-profits pyarmor-regcode-xxxx.txt` worked fine and generated a zip file
- `pyarmor -v` give us this output : 
```
C:\Users\Administrateur\Documents> pyarmor -v
Pyarmor 8.3.6 (trial), 000000, non-profits

License Type    : pyarmor-trial
License No.     : pyarmor-vax-000000
License To      : 
License Product : non-profits

BCC Mode        : No
RFT Mode        : No

Notes
* Can't obfuscate big script and mix str    
```

- Then we tried `pyarmor -d reg -g 1` which gave us this output : 
```
C:\Users\Administrateur\Documents>pyarmor -d reg -g 1
INFO     Python 3.11.5
INFO     Pyarmor 8.3.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64
DEBUG    native platform windows.amd64
DEBUG    home path: C:\Users\Administrateur\.pyarmor
INFO     generating device file ".pyarmor\group\pyarmor-group-device.1"
DEBUG    unknown error, please check pyarmor.error.log
ERROR    <built-in function get_hd_info> returned a result with an exception set  
```

- And here's the content of `pyarmor.error`
```
2472 MainProcess 2023-09-15 10:20:10,775
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 25: invalid continuation byte

The above exception was the direct cause of the following exception:

SystemError: <class 'UnicodeDecodeError'> returned a result with an exception set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 702, in main
    main_entry(sys.argv[1:])
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 690, in main_entry
    return args.func(ctx, args)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\__main__.py", line 248, in cmd_reg
    reg.generate_group_device(args.device)
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\register.py", line 221, in generate_group_device
    machid = self._get_machine_id(devflag).decode('utf-8')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\register.py", line 211, in _get_machine_id
    return Pytransform3.get_hd_info(devflag)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyarmor\cli\core\__init__.py", line 134, in get_hd_info
    else m.get_hd_info(hdtype)
         ^^^^^^^^^^^^^^^^^^^^^
SystemError: <built-in function get_hd_info> returned a result with an exception set
```

I noticed running `get_hd_info(11)` returns the error seen above. Only `get_hd_info(10)` returns an actual ID.

I don't think we missed a step in the registering process and I couldn't find any other related issue,

- `pyarmor gen -O dist --assert-call foo.py`
```
C:\Users\Administrateur\Documents> pyarmor gen -O dist --assert-call foo.py
INFO     Python 3.11.5
INFO     Pyarmor 8.3.6 (trial), 000000, non-profits
INFO     Platform windows.x86_64 
```

**Comment by tagnelli** [comment] 2023-09-15 09:14
Tested on `Debian Linux 12`, the `pyarmor reg -g 2` command is working fine and generated a file under `.pyarmor/pyarmor-group-device.2`

**Comment by jondy** [comment] 2023-09-15 23:48
Thanks, Pyarmor 8.3.7 has been released with this machine flag patch.

But I can't reproduce this issue `<built-in function get_hd_info> returned a result with an exception set` in windows.x86_64

**Closed** 2023-09-18 14:17 UTC
Labels: bug
