### ISSUE TITLE
Pyarmor pack missing in pyarmor 8.0

### ISSUE THREAD

**Issue by SamComber** [dashingsoft/pyarmor#974] opened 2023-03-15 08:00 UTC
From the cli arguments I can see the pack command is no longer listed, we rely on this and use the pyinstaller approach using a .spec file to obfuscate…

In pyarmor 8.0, how can we achieve the same thing without the pack command being available ?

**Comment by SamComber** [comment] 2023-03-17 00:15
Our current usage is like

`pyarmor pack --clean --with-license $PYARMOR_LICENSE -s ./my_spec.spec ./main.py
`

Is the new suggested approach like so from the docs https://pyarmor.readthedocs.io/en/latest/tutorial/obfuscation.html#packing-to-one-folder? I'm just trying to work out how to get identical behaviour between versions.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/9962584/225779925-2b980d72-c2e8-4860-8a38-360bfcd7d3c6.png">

**Comment by jondy** [comment] 2023-03-17 01:47
There is no identical pack in Pyarmor 8.0.

Pyarmor 8.0 only provide repack function to handle bundle of PyInstaller.

**Comment by SamComber** [comment] 2023-03-17 10:15
@jondy , I tried this suggestion, but got the following error,  `pyarmor gen -O obfdist --pack dist/test_pyarmor/test_pyarmor test_pyarmor.py`

`ERROR    No module named 'PyInstaller.loader.pyimod02_archive'`

**Comment by SamComber** [comment] 2023-03-17 10:35
Just a heads up @jondy , `PyInstaller.loader.pyimod02_archive` has been removed from pyinstaller v5.3+ onwards and is now pyimod01_archive it seems

<img width="506" alt="image" src="https://user-images.githubusercontent.com/9962584/225881239-992c75af-4141-497c-b315-c7cf493e0011.png">

**Comment by SamComber** [comment] 2023-03-17 10:50
But you can't install pyinstaller==5.2.0 with py311 because `5.2 Requires-Python <3.11,>=3.7;`

**Comment by jondy** [comment] 2023-03-17 12:25
@SamComber thank you very much.

What's the content of `pyarmor.error.log`?

**Comment by SamComber** [comment] 2023-03-17 12:35
@jondy 

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/generate.py", line 159, in process
    self._pack_script(pack, output)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/generate.py", line 93, in _pack_script
    repacker(bundle, output, build, entry=entry, codesign=codesign)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/repack.py", line 277, in repacker
    repack_exe(path, obfname, logic_toc, obfentry, codesign=codesign)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/repack.py", line 173, in repack_exe
    offset, pylib_name = get_carchive_info(obfname)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/repack.py", line 88, in get_carchive_info
    return pos, pylibname.decode()
                ^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 24: invalid start byte

**Comment by jondy** [comment] 2023-03-17 12:52
Got it, thanks

**Comment by SamComber** [comment] 2023-03-20 11:32
Hey @jondy, will we be able to use a patched version for this `UnicodeDecodeError` error soon?

**Comment by SamComber** [comment] 2023-03-20 13:37
No, I just run it on the output from `pyinstaller test.py`

i.e. `pyarmor gen -O obfdist --pack dist/test/test test.py` 

My folder tree is like 

```
├── build
│   └── test
│       ├── Analysis-00.toc
│       ├── COLLECT-00.toc
│       ├── EXE-00.toc
│       ├── PKG-00.toc
│       ├── PYZ-00.pyz
│       ├── PYZ-00.toc
│       ├── base_library.zip
│       ├── localpycs
│       │   ├── pyimod01_archive.pyc
│       │   ├── pyimod02_importers.pyc
│       │   ├── pyimod03_ctypes.pyc
│       │   └── struct.pyc
│       ├── test
│       ├── test.pkg
│       ├── warn-test.txt
│       └── xref-test.html
├── core
├── dist
│   └── test
│       ├── base_library.zip
│       ├── lib-dynload
│       │   ├── _asyncio.cpython-311-x86_64-linux-gnu.so
│       │   ├── _bz2.cpython-311-x86_64-linux-gnu.so
│       │   ├── _codecs_cn.cpython-311-x86_64-linux-gnu.so
│       │   ├── _codecs_hk.cpython-311-x86_64-linux-gnu.so
│       │   ├── _codecs_iso2022.cpython-311-x86_64-linux-gnu.so
│       │   ├── _codecs_jp.cpython-311-x86_64-linux-gnu.so
│       │   ├── _codecs_kr.cpython-311-x86_64-linux-gnu.so
│       │   ├── _codecs_tw.cpython-311-x86_64-linux-gnu.so
│       │   ├── _contextvars.cpython-311-x86_64-linux-gnu.so
│       │   ├── _ctypes.cpython-311-x86_64-linux-gnu.so
│       │   ├── _decimal.cpython-311-x86_64-linux-gnu.so
│       │   ├── _hashlib.cpython-311-x86_64-linux-gnu.so
│       │   ├── _json.cpython-311-x86_64-linux-gnu.so
│       │   ├── _lzma.cpython-311-x86_64-linux-gnu.so
│       │   ├── _multibytecodec.cpython-311-x86_64-linux-gnu.so
│       │   ├── _multiprocessing.cpython-311-x86_64-linux-gnu.so
│       │   ├── _posixshmem.cpython-311-x86_64-linux-gnu.so
│       │   ├── _queue.cpython-311-x86_64-linux-gnu.so
│       │   ├── _ssl.cpython-311-x86_64-linux-gnu.so
│       │   ├── _typing.cpython-311-x86_64-linux-gnu.so
│       │   ├── mmap.cpython-311-x86_64-linux-gnu.so
│       │   ├── readline.cpython-311-x86_64-linux-gnu.so
│       │   ├── resource.cpython-311-x86_64-linux-gnu.so
│       │   └── termios.cpython-311-x86_64-linux-gnu.so
│       ├── libbz2.so.1.0
│       ├── libcrypto.so.3
│       ├── libffi.so.8
│       ├── libgcc_s.so.1
│       ├── libgfortran-040039e1.so.5.0.0
│       ├── liblzma.so.5
│       ├── libopenblas64_p-r0-742d56dc.3.20.so
│       ├── libpython3.11.so.1.0
│       ├── libquadmath-96973f99.so.0.0.0
│       ├── libreadline.so.8
│       ├── libssl.so.3
│       ├── libtinfo.so.6
│       ├── libz.so.1
│       ├── numpy
│       │   ├── core
│       │   │   ├── _multiarray_tests.cpython-311-x86_64-linux-gnu.so
│       │   │   └── _multiarray_umath.cpython-311-x86_64-linux-gnu.so
│       │   ├── fft
│       │   │   └── _pocketfft_internal.cpython-311-x86_64-linux-gnu.so
│       │   ├── linalg
│       │   │   ├── _umath_linalg.cpython-311-x86_64-linux-gnu.so
│       │   │   └── lapack_lite.cpython-311-x86_64-linux-gnu.so
│       │   └── random
│       │       ├── _bounded_integers.cpython-311-x86_64-linux-gnu.so
│       │       ├── _common.cpython-311-x86_64-linux-gnu.so
│       │       ├── _generator.cpython-311-x86_64-linux-gnu.so
│       │       ├── _mt19937.cpython-311-x86_64-linux-gnu.so
│       │       ├── _pcg64.cpython-311-x86_64-linux-gnu.so
│       │       ├── _philox.cpython-311-x86_64-linux-gnu.so
│       │       ├── _sfc64.cpython-311-x86_64-linux-gnu.so
│       │       ├── bit_generator.cpython-311-x86_64-linux-gnu.so
│       │       └── mtrand.cpython-311-x86_64-linux-gnu.so
│       └── test
├── obfdist
│   ├── pyarmor_runtime_000000
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   │   └── __init__.cpython-311.pyc
│   │   └── pyarmor_runtime.so
│   └── test.py
├── pyarmor.error.log
├── test.py
└── test.spec
```

**Comment by SamComber** [comment] 2023-03-20 17:10
Changing my script a bit, getting a different bug now

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/__main__.py", line 559, in main
    main_entry(sys.argv[1:])
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/__main__.py", line 547, in main_entry
    args.func(ctx, args)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/__main__.py", line 144, in cmd_gen
    builder.process(options, pack=args.pack)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/generate.py", line 159, in process
    self._pack_script(pack, output)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/generate.py", line 93, in _pack_script
    repacker(bundle, output, build, entry=entry, codesign=codesign)
  File "/usr/local/lib/python3.11/dist-packages/pyarmor/cli/repack.py", line 277, in repacker
    shutil.copy2(item[-1], os.path.join(dest, item[-2]))
  File "/usr/lib/python3.11/shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dist/test/pyarmor_runtime_000000/pyarmor_runtime.so'
```

**Comment by jondy** [comment] 2023-03-21 05:50
`UnicodeDecodeError ` has been fixed in 8.0.7

**Comment by SamComber** [comment] 2023-03-21 06:32
Thanks @jondy, this error has disappeared now 👍 !!!! I just have one question, are we supposed to use the patched bundle or are we supposed to use the output folder from `-O` part of command as new bundled executable? 

I can see from the logs

**Comment by SamComber** [comment] 2023-03-21 07:54
And just a heads up, when I attempted a more non-trivial example, I got this error 

`[7138] Error loading Python lib '/tmp/_MEIAOXGwn/libpython3.11.so.1.0': dlopen: /tmp/_MEIAOXGwn/libpython3.11.so.1.0: cannot open shared object file: No such file or directory` 

Is it looking in the wrong place? I can see the correct .so inside `/dist/non_trivial_project/`

```
root@577487935cb4:/non_trivial_project# ls -lh dist/non_trivial_project/libpython*
-rwxr-xr-x 1 root root 7.5M Feb  8 14:49 dist/non_trivial_project/libpython3.11.so.1.0
```

**Comment by jondy** [comment] 2023-03-21 09:13
> Does this mean the packaged bundle dist/test/test has now been obfuscated by pyarmor and I should use this?

Yes. For example,

```
pyarmor gen --pack dist/test/test test.py
```

This command will overwrite `dest/test/test` with obfuscated one.

**Comment by SamComber** [comment] 2023-03-22 23:06
Any suggestion on what to do with this error below @jondy ? I've ran out of ideas when testing, not sure why it's attempting to load libpython3.11.so.1.0 from /tmp, annoyingly the folder tmp/_MEIAOXGwn regenerates so I can't move it to even get past this

`[7138] Error loading Python lib '/tmp/_MEIAOXGwn/libpython3.11.so.1.0': dlopen: /tmp/_MEIAOXGwn/libpython3.11.so.1.0: cannot open shared object file: No such file or directory`

**Comment by jondy** [comment] 2023-03-22 23:46
PyInstaller will extract bundle to random temporary folder, here it is `/tmp/_MEIAOXGwn/`

I'll check this today.

**Comment by jondy** [comment] 2023-03-22 23:47
PyInstaller will extract bundle to random temporary folder, here it is `/tmp/_MEIAOXGwn/`

I'll check this today.

**Comment by SamComber** [comment] 2023-03-28 13:52
I'm using a .spec file, and the pyinstaller bundle works without obfuscation with `pyarmor gen --pack command`

Can you reproduce with the issue with this small example @jondy ?

**`test.spec`:**

```
# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for model-trainer"""
from PyInstaller.building.api import PYZ, EXE, COLLECT
from PyInstaller.building.build_main import Analysis
import importlib
import os

BLOCK_CIPHER = None

INTERNAL_DATA_FILES = []
EXTERNAL_DATA_FILES = []

DATA_FILES = INTERNAL_DATA_FILES.copy()

HIDDEN_IMPORTS = []

BINARIES = []

a = Analysis(
    ['test.py'],
    pathex=[],
    binaries=BINARIES,
    datas=DATA_FILES,
    hiddenimports=HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=BLOCK_CIPHER,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=BLOCK_CIPHER)

exe = EXE(
    pyz,
    a.scripts,
    [("W ignore", None, "OPTION")],
    exclude_binaries=True,
    name='model_runner',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='model_runner',
)
```

**`test.py`:**

```
import ctypes
import errno
import glob
import importlib
import logging
import os
import sys
import traceback
from typing import Dict

import yaml
import numpy

print(numpy)
```

And then test commands

```
# produces dist/test/test
pyinstaller test.spec 

# verify working before pyarmor 
dist/test/test

# obfuscate
pyarmor gen --pack dist/test/test

# verify working after pyarmor 
dist/test/test
```

Where I get this error `[1191] Error loading Python lib '/tmp/_MEIOxAbcR/libpython3.11.so.1.0': dlopen: /tmp/_MEIOxAbcR/libpython3.11.so.1.0: cannot open shared object file: No such file or directory`

Python 3.11, pyarmor 8.0.20, pyinstaller 5.6.2

**Comment by jondy** [comment] 2023-03-28 15:03
Could you check the dependency of pyarmor_runtime.so?
```
ldd dist/test/pyarmor_runtime_xxxxxx/pyarmor_runtime.so
```

And for a test with `--onefile`, does it work?
```
# produces dist/test
pyinstaller --onefile test.py 

# verify working before pyarmor 
dist/test

# obfuscate
pyarmor gen --pack dist/test test.py

# verify working after pyarmor 
dist/test
```

**Comment by jondy** [comment] 2023-03-29 23:24
@SamComber I have not reproduced it. But I think I find the problem, because `pyarmor_runtime.so` isn't in the same path with `libpythonxxx.1.0`. 

It will be fixed in next release.

**Comment by jondy** [comment] 2023-03-30 01:10
@SamComber

You can try this method to pack the scripts, actually this is what old Pyarmor pack does. Please replace `_src` and `_obf` with right path in the patched code.
 
1. First generate ``.spec`` by PyInstaller
2. Then obfuscate the scripts by Pyarmor
3. Next patch ``.spec``

```python
a = Analysis(....)

    # Patched by PyArmor
    _src = r'/Users/jondy/workspace/pyarmor/test'
    _obf = r'/Users/jondy/workspace/pyarmor/test/dist/obf'
    
    _count = 0
    for i in range(len(a.scripts)):
        if a.scripts[i][1].startswith(_src):
            x = a.scripts[i][1].replace(_src, _obf)
            if os.path.exists(x):
                a.scripts[i] = a.scripts[i][0], x, a.scripts[i][2]
                _count += 1
    if _count == 0:
        raise RuntimeError('No obfuscated script found')
    for i in range(len(a.pure)):
        if a.pure[i][1].startswith(_src):
            x = a.pure[i][1].replace(_src, _obf)
            if os.path.exists(x):
                if hasattr(a.pure, '_code_cache'):
                    with open(x) as f:
                        a.pure._code_cache[a.pure[i][0]] = compile(f.read(), a.pure[i][1], 'exec')
                a.pure[i] = a.pure[i][0], x, a.pure[i][2]
    # Patch end.

pyz = PYZ(a.pure, a.zipped_data, cipher=BLOCK_CIPHER)
```
4. Finally run the patched ``.spec`` by PyInstaller

**Comment by jondy** [comment] 2023-03-30 01:21
Sorry, forget one thing, it still appends hidden import to package `pyarmor_runtime_000000`
```python
HIDDEN_IMPORTS = ['pyarmor_runtime_000000']

a = Analysis(
    ['test.py'],
    pathex=['/path/to/obf'],
    ...)
```

**Comment by SamComber** [comment] 2023-03-31 16:06
@jondy thank you so much! 

This is working well and I can see that the obfuscation is further working by removing `pyarmor_runtime_000000` from `dist/test/test` it complains ...

`ModuleNotFoundError: No module named 'pyarmor_runtime_000000.pyarmor_runtime'`

as we would expect it to, so I'm confident `--pack` is working well with the patched spec - thank you!

I just have one last question and then we can close this issue.. is there an option to rename `pyarmor_runtime_000000` somewhere? I'd like to be able to hide obfuscation technique, and right now anyone with access to the bundle can pretty clearly see this is a pyarmor-based obfuscation. Is this possible?

**Comment by jondy** [comment] 2023-04-01 00:55
No, the runtime package name can't be changed.

**Comment by SamComber** [comment] 2023-04-01 08:03
Okay thanks @jondy - feel free to close, nice work!

**Closed** 2023-04-01 08:40 UTC
Labels: enhancement
